### ISSUE TITLE
Help to run project - Training matter

### ISSUE THREAD

**Issue by houcine** [StefanIordache/NewsIO#9]
**Please can you help me debug and run this project ?**
@StefanIordache @AlinaMaican 
_Thanks in advance !_
Kind Regards :+1:

**Comment by StefanIordache** [comment]
Hello!

In order to start this project you should have installed:
* .NET Core 2.0
* Node.js
* Visual Studio or Visual Studio Code to run from console

In order to run this project use "dotnet" commands.
